### ISSUE TITLE
Could you provide a mock preload data files?

### ISSUE THREAD

**Issue by freestatman** [tbilab/multimorbidity_explorer#8]
Great work and nice presentation in rstudio::conf! 
I’m interested in running the app and wondering if you can add a mock input data for the preload data feature? Thanks.

Freeman

**Comment by nstrayer** [comment]
Hi @freestatman !  

Indeed! I also realized that it may help to have the docker image be able to run without needing any other commands. In the next week or so I will add some mock data to a public version of the app! 

Thanks for reaching out and I'll ping you here when it's done!

**Comment by freestatman** [comment]
Sounds good. Thank you very much @nstrayer ! And thanks for your nice examples of r2d3 visualization, and I'm looking forwards to exploring more of it.

**Comment by nstrayer** [comment]
Hi @freestatman , 

There is now a hosted version of the app that allows you to upload your own data (although keep in mind that the data gets manipulated on our servers so sensitive data should probably not go there). 

If you go to [this app link](https://prod.tbilab.org/me_w_test_data/) and use the preloaded snp in the dropdown menu in the upper left. The data are entirely simulated so there may be some weird patterns as a result (I haven't done super thorough testing of the simulation algorithm yet to see how robust it is).

Let me know if you have any questions!

**Comment by nstrayer** [comment]
Also -- if you have your own phewas result and want to simulate your own individual data a function `simIndividualData` has been added to the `meToolkit` package. Here's [the test script](https://github.com/tbilab/meToolkit/blob/individual_data_simulation_overhaul/tests/testthat/test-simindividualdata.R) to demo how it works.
